services:
  - type: web
    name: school-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: <your-db-host>
      - key: DB_USER
        value: <your-db-user>
      - key: DB_PASS
        value: <your-db-password>
      - key: DB_NAME
        value: <your-db-name>
    autoDeploy: true
